version: '3'

services:
  web:
    build: .
    ports:
      - 8080:8080
  db:
    image: postgres
    environment:
      POSTGRES_USER: podil
      POSTGRES_PASSWORD: central
      POSTGRES_DB: podil_central
    ports:
      - 5432:5432